"""Operating-window sweep convergence tests.

The Phase 1 gate requires the twin to converge across the full
intended LV operating window without manual intervention. These tests
exercise the sweep machinery on a small grid (kept under 60 points
for CI speed) and assert >=99 % convergence and physically plausible
output ranges.
"""

from __future__ import annotations

import numpy as np
import numpy.typing as npt
import pandas as pd

from industrial_ai.twin.column_a import DEFAULT_PARAMETERS
from industrial_ai.twin.column_a.operating_window import (
    GridSpec,
    build_grid,
    default_lv_grid_spec,
    sweep_operating_window,
)


def _small_grid_spec() -> GridSpec:
    """Smaller grid (3 x 3 x 3 x 2 = 54 points) used to keep CI fast.

    The convergence story is identical at any grid size; the larger
    >=1000-point sweep is generated by ``tools/run_operating_window_sweep.py``.
    Ratios stay inside the +/-10 % LV window defined in
    :func:`default_lv_grid_spec` for the same physical-realizability
    reasons.
    """
    return GridSpec(
        F=(0.85, 1.0, 1.15),
        zF=(0.4, 0.5, 0.6),
        LT_ratios=(0.95, 1.0, 1.05),
        VB_ratios=(0.95, 1.05),
    )


def test_default_grid_spec_yields_at_least_1000_points() -> None:
    """The default LV grid must hit the >=1000 baseline operating points target."""
    spec = default_lv_grid_spec()
    assert spec.n_points() >= 1000


def test_build_grid_emits_correct_layout() -> None:
    """Each grid point must carry the five LV free parameters."""
    spec = _small_grid_spec()
    grid = list(build_grid(spec))
    assert len(grid) == spec.n_points()
    for point in grid:
        assert point.qF == 1.0
        assert 0.0 < point.zF < 1.0
        assert point.LT > 0.0 and point.VB > 0.0
        assert point.F > 0.0


def test_small_grid_converges_at_99_percent(
    skogestad_reference_state: npt.NDArray[np.float64],
) -> None:
    """A 54-point sweep warm-started from the published SS must converge >=99 % of the time."""
    spec = _small_grid_spec()
    df = sweep_operating_window(spec, X_init=skogestad_reference_state)
    assert isinstance(df, pd.DataFrame)
    assert len(df) == spec.n_points()
    success_rate = float(df["success"].mean())
    assert success_rate >= 0.99, (
        f"sweep success rate {success_rate:.1%} below 99 % gate; "
        f"failures at {df.loc[~df['success'], ['F', 'zF', 'LT', 'VB']].to_dict('records')}"
    )
    # Compositions must remain physical at every converged point.
    converged = df[df["success"]]
    assert (converged["y_D"] >= 0.0).all()
    assert (converged["y_D"] <= 1.0).all()
    assert (converged["x_B"] >= 0.0).all()
    assert (converged["x_B"] <= 1.0).all()
    # At the central nominal point the column should still hit >= 95 % purity.
    nominal_mask = (
        np.isclose(df["F"], 1.0)
        & np.isclose(df["zF"], 0.5)
        & np.isclose(df["LT"], DEFAULT_PARAMETERS.nominal_reflux_L0_kmol_per_min)
    )
    if nominal_mask.any():
        nominal_row = df[nominal_mask].iloc[0]
        assert nominal_row["y_D"] > 0.95, (
            f"central operating point yields y_D={nominal_row['y_D']:.4f} (<0.95)"
        )


def test_cold_start_sweep_still_largely_converges(
    skogestad_reference_state: npt.NDArray[np.float64],
) -> None:
    """Without warm-starting between points, convergence drops but stays usable.

    This regression-guards against accidentally removing the warm-start
    optimization: warm-start should materially help, not be a no-op.
    """
    spec = GridSpec(F=(0.9, 1.0, 1.1), zF=(0.4, 0.6), LT_ratios=(0.95, 1.05), VB_ratios=(1.0,))
    df_cold = sweep_operating_window(spec, X_init=skogestad_reference_state, warm_start=False)
    df_warm = sweep_operating_window(spec, X_init=skogestad_reference_state, warm_start=True)
    # Both must hit acceptable convergence for these mild perturbations;
    # warm-start cannot be worse than cold-start (it is monotone in
    # initial-guess quality for Newton-Krylov with bounded steps).
    assert df_warm["success"].mean() >= df_cold["success"].mean()
    assert df_warm["success"].mean() == 1.0
